package cz.hspinovace.psmf.tools.leagueimport

import cz.hspinovace.psmf.data.seed.SeedFileReader
import cz.hspinovace.psmf.data.seed.SeedGroupDto
import cz.hspinovace.psmf.data.seed.SeedIndexDto
import cz.hspinovace.psmf.data.seed.SeedLeagueCatalog
import cz.hspinovace.psmf.data.seed.SeedVenuesDto
import kotlinx.coroutines.runBlocking
import kotlinx.datetime.LocalDate
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import java.io.File

/**
 * Reading and writing the seed files, through the app's own DTOs and
 * nothing else -- the file format has one definition, in `:shared`.
 */
object SeedJson {
    /** Read exactly as the app reads: unknown keys, like `$comment`, ignored. */
    private val READ: Json = SeedLeagueCatalog.DEFAULT_JSON

    /** Two-space indent, every field present, the shape the README shows. */
    @OptIn(ExperimentalSerializationApi::class)
    private val WRITE: Json =
        Json {
            prettyPrint = true
            prettyPrintIndent = "  "
            explicitNulls = true
            encodeDefaults = true
        }

    /** What [directory] already holds; nothing if it holds nothing. */
    fun read(directory: File): ExistingSeed {
        fun text(name: String) = File(directory, name).takeIf { it.isFile }?.readText()
        val index = text(SeedLeagueCatalog.INDEX_FILE)?.let { READ.decodeFromString<SeedIndexDto>(it) }
        return ExistingSeed(
            index = index,
            groups =
                index?.groups.orEmpty().mapNotNull { entry ->
                    text(entry.file)?.let { READ.decodeFromString<SeedGroupDto>(it) }
                },
            venues = text(SeedLeagueCatalog.VENUES_FILE)?.let { READ.decodeFromString<SeedVenuesDto>(it) },
        )
    }

    /** File name to contents, each opening with a `$comment` saying where it came from. */
    fun render(
        output: SeedOutput,
        asOf: LocalDate,
    ): Map<String, String> {
        val note = listOf("Generated by tools/league-import from psmf.cz; data as of $asOf.")
        return buildMap {
            put(SeedLeagueCatalog.INDEX_FILE, encode(SeedIndexDto.serializer(), output.index, note))
            put(SeedLeagueCatalog.VENUES_FILE, encode(SeedVenuesDto.serializer(), output.venues, note + VENUES_NOTE))
            output.groups.forEach { put("${it.id}.json", encode(SeedGroupDto.serializer(), it, note + GROUP_NOTE)) }
        }
    }

    /**
     * Loads [files] through the app's own `SeedLeagueCatalog`, exactly as a
     * phone would, and throws its `SeedException` if anything is wrong. Run
     * before anything is written, so a bad run writes nothing.
     */
    fun loadAsTheAppWould(files: Map<String, String>) =
        runBlocking { SeedLeagueCatalog(SeedFileReader { files[it] }).loadAll() }

    private fun <T> encode(
        serializer: KSerializer<T>,
        value: T,
        comment: List<String>,
    ): String {
        val body = WRITE.encodeToJsonElement(serializer, value).jsonObject
        val withComment = JsonObject(mapOf("\$comment" to JsonArray(comment.map(::JsonPrimitive))) + body)
        return WRITE.encodeToString(JsonObject.serializer(), withComment) + "\n"
    }

    private val GROUP_NOTE =
        listOf(
            "Ids are permanent: re-run the importer, never regenerate this file. See README.md.",
            "Players have no RP number, date of birth or jersey number: psmf.cz publishes none.",
        )
    private val VENUES_NOTE = listOf("Every pitch /hriste/ lists; codes are league-wide.")
}
